#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@invoiceId = 6751577878-20260629-514966000000-3F

### Delete non-existing invoice
DELETE {{baseUrl}}/app/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing invoice
DELETE {{baseUrl}}/app/invoices?id={{invoiceId}}
Content-Type: application/json
X-API-Key: {{apiKey}}