#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@invoiceId = 6751577878-20260629-514966000000-3F

### List all
GET {{baseUrl}}/db/invoices
Content-Type: application/json
X-API-Key: {{apiKey}}

### List non-existing invoice
GET {{baseUrl}}/db/invoices?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List existing invoice
GET {{baseUrl}}/db/invoices?id={{invoiceId}}
Content-Type: application/json
X-API-Key: {{apiKey}}