#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@taxRecordId = 9de76eee-87fe-44b7-adbe-c9c596113aa9

### Update a missing tax record
PUT {{baseUrl}}/db/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "id": "missing",
    "notes": "nevermind"
}

### Update existing tax record
PUT {{baseUrl}}/db/taxes
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "id": "{{taxRecordId}}",
    "notes": "edited"
}