#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@invoiceId = eFV/2026/06/29/1/KSeF

### Delete non-existing invoice
DELETE {{baseUrl}}/app/invoices?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing invoice
DELETE {{baseUrl}}/app/invoices?id={{invoiceId}}
Content-Type: application/json
X-API-Key: {{apiKey}}