#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Create invoice for the first time
POST {{baseUrl}}/app/invoices
Content-Type: multipart/form-data; boundary=ksefInvoice
X-API-Key: {{apiKey}}

--ksefInvoice
Content-Disposition: form-data; name="file"; filename="invoice-1.xml"
Content-Type: application/xml

< ../../../testresources/ksef-pii/sales/6751577878-20260629-514966000000-3F.anonymized.xml
--ksefInvoice
Content-Disposition: form-data; name="notes"

Test notes
--ksefInvoice--

### Second create attempt whould trigger PK violation error
POST {{baseUrl}}/app/invoices
Content-Type: multipart/form-data; boundary=ksefInvoice
X-API-Key: {{apiKey}}

--ksefInvoice
Content-Disposition: form-data; name="file"; filename="invoice-1.xml"
Content-Type: application/xml

< ../../../testresources/ksef-pii/sales/6751577878-20260629-514966000000-3F.anonymized.xml
--ksefInvoice--