#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Update invoices is not supported
PUT {{baseUrl}}/app/invoices
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "id": "missing", "notes": "nevermind" }