name = "ksef-bot"
main = "worker-ksef/ksef.worker.ts"
compatibility_date = "2026-01-01"

[vars]
ENVIRONMENT = "cloudflare"
# ...Rest of required env coming from Cloudflare secrets

[observability.logs]
enabled = true
invocation_logs = true
[observability.traces]
enabled = true

# Deploy some of the static assets for the /docs
[assets]
binding = "assets"
directory = "./dist"

[[d1_databases]]
binding = "D1"
database_name = "ksef-bot"
database_id = "d54f4ce1-28fb-4d99-bbb4-e11387753fc7"
remote = true