#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Create contractor #1 for the first time
POST {{baseUrl}}/app/contractors
Content-Type: application/json
X-API-Key: {{apiKey}}

< ../../../testresources/contractors/contractor-1.json

### Create contractor #2 for the first time
POST {{baseUrl}}/app/contractors
Content-Type: application/json
X-API-Key: {{apiKey}}

< ../../../testresources/contractors/contractor-2.json

### Second create attempt whould trigger PK violation error
POST {{baseUrl}}/app/contractors
Content-Type: application/json
X-API-Key: {{apiKey}}

< ../../../testresources/contractors/contractor-2.json