#@no-redirect
@workerUrl = http://localhost:3001
@userNip = 6751577878
@customerNip = 5170312965

### For user CEIDG should succeed
GET {{workerUrl}}/app/contractor?profile=user&nip={{userNip}}
Accept: application/json

### For customer CEIDG should fail, KRS should fail, VAT_LB should succeed
GET {{workerUrl}}/app/contractor?profile=user&nip={{userNip}}
Accept: application/json

### For customer KRS should succeed
GET {{workerUrl}}/app/contractor?profile=customer&nip={{customerNip}}
Accept: application/json

### For user KRS should fail, CEIDG should succeed
GET {{workerUrl}}/app/contractor?profile=customer&nip={{userNip}}
Accept: application/json

### For non-existing NIP - CEIDG -> KRS -> VAT_LB should all fail
GET {{workerUrl}}/app/contractor?profile=customer&nip=missing
Accept: application/json