#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@from = 2026/06/01
@to = 2026/08/01
@sessionReferenceNumber = 20260831-SO-46054A6000-3BC9293EE2-6A
@invoiceReferenceNumber = 20260831-EE-4605576000-FC449AC181-66

### List for non-existing dates
GET {{baseUrl}}/ksef/sales?from=missing&to=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List for existing dates
GET {{baseUrl}}/ksef/sales?from={{from}}&to={{to}}
Content-Type: application/json
X-API-Key: {{apiKey}}

### List all sessions
GET {{baseUrl}}/ksef/sales/session
X-API-Key: {{apiKey}}

### List specific session status
GET {{baseUrl}}/ksef/sales/session?sessionReferenceNumber={{sessionReferenceNumber}}
X-API-Key: {{apiKey}}

### List session invoices
GET {{baseUrl}}/ksef/sales/session/invoices?sessionReferenceNumber={{sessionReferenceNumber}}
X-API-Key: {{apiKey}}

### Check submission status
GET {{baseUrl}}/ksef/sales/status?sessionReferenceNumber={{sessionReferenceNumber}}&invoiceReferenceNumber={{invoiceReferenceNumber}}
X-API-Key: {{apiKey}}
Accept: application/json