#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@from = 2026/06/01
@to = 2026/08/01
@sessionReferenceNumber = 20260831-SO-41C0CF4000-44E9109AB4-C0
@invoiceReferenceNumber = 20260831-EE-40841FF000-3FD2C75D72-27

### List for non-existing dates
GET {{baseUrl}}/ksef/sales?from=missing&to=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List for existing dates
GET {{baseUrl}}/ksef/sales?from={{from}}&to={{to}}
Content-Type: application/json
X-API-Key: {{apiKey}}

### Check session status
GET {{baseUrl}}/ksef/sales/session?sessionReferenceNumber={{sessionReferenceNumber}}
X-API-Key: {{apiKey}}

### Check submission status
GET {{baseUrl}}/ksef/sales/status?sessionReferenceNumber={{sessionReferenceNumber}}&invoiceReferenceNumber={{invoiceReferenceNumber}}
X-API-Key: {{apiKey}}
Accept: application/json