#@no-redirect
@baseUrl = https://dane.biznes.gov.pl/api/ceidg/v3
@apiKey = eyJraWQiOiJjZWlkZyIsImFsZyI6IkhTNTEyIn0.eyJnaXZlbl9uYW1lIjoiRGllZ28iLCJwZXNlbCI6IjgzMDcxNjIxNDM1IiwiaWF0IjoxNzg3MjExMTA2LCJmYW1pbHlfbmFtZSI6IlJ1aXoiLCJjbGllbnRfaWQiOiJVU0VSLTgzMDcxNjIxNDM1LURJRUdPLVJVSVoifQ.e-xEW3LjJ2JAusMW-BbtYjsToAmj0KEfqC_mG_94opF4APcS0J7KUOzLBNvqsubNJhRJUu7yGjju_3i3WbvSFQ
@company = 12C97AC8-D3CF-4CF1-878D-158A7E8BDF51

### List one's company by NIP
GET {{baseUrl}}/firmy?nip=6751577878
Accept: application/json
Authorization: Bearer {{apiKey}}

### List company details
GET {{baseUrl}}/firma/{{company}}
Accept: application/json
Authorization: Bearer {{apiKey}}

### List another one's company by NIP
GET {{baseUrl}}/firmy?nip=5170312965
Accept: application/json
Authorization: Bearer {{apiKey}}