#@no-redirect
@workerUrl = http://localhost:3001
@apiKey = test
@userNip = 7272445205
@customerNip = 6252447933

### For user CEIDG should succeed
GET {{workerUrl}}/gov/contractors?nip={{userNip}}&profile=user
Accept: application/json
X-API-Key: {{apiKey}}

### For user KRS should fail but CEIDG should succeed
GET {{workerUrl}}/gov/contractors?nip={{userNip}}&profile=customer
Accept: application/json
X-API-Key: {{apiKey}}

### For customer KRS should succeed
GET {{workerUrl}}/gov/contractors?nip={{customerNip}}&profile=customer
Accept: application/json
X-API-Key: {{apiKey}}

### For customer CEIDG should fail but KRS should succeed
GET {{workerUrl}}/gov/contractors?nip={{customerNip}}&profile=user
Accept: application/json
X-API-Key: {{apiKey}}

### For invalid NIP everything should all fail
GET {{workerUrl}}/gov/contractors?nip=missing&profile=user
Accept: application/json
X-API-Key: {{apiKey}}

### For invalid NIP everything should all fail
GET {{workerUrl}}/gov/contractors?nip=missing&profile=customer
Accept: application/json
X-API-Key: {{apiKey}}

### For non-existing NIP everything should all fail
GET {{workerUrl}}/gov/contractors?nip=1234567890&profile=user
Accept: application/json
X-API-Key: {{apiKey}}

### For non-existing NIP everything should all fail
GET {{workerUrl}}/gov/contractors?nip=1234567890&profile=customer
Accept: application/json
X-API-Key: {{apiKey}}