#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@userEmail = user@mail.com

### List all should always return the admin user
GET {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

### List non-existing user should fail
GET {{baseUrl}}/app/users?email=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List existing user
GET {{baseUrl}}/app/users?email={{userEmail}}
Content-Type: application/json
X-API-Key: {{apiKey}}