#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = JP4t96R8FD___z60VX84r

### Delete non-existing counterparty
DELETE {{baseUrl}}/app/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing counterparty
DELETE {{baseUrl}}/app/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}