#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = 1SkIa0fw2CZ61lqnhhkJ_

### Delete non-existing counterparty
DELETE {{baseUrl}}/app/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing counterparty
DELETE {{baseUrl}}/app/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}