#@no-redirect
@baseUrl = http://localhost:3002
@apiKey = test
@counterpartyId = counterparty-from-invoice

### List all
GET {{baseUrl}}/db/counterparties
Content-Type: application/json
X-API-Key: {{apiKey}}

### List by Id
GET {{baseUrl}}/db/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}

### List by wrong Id
GET {{baseUrl}}/db/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}