#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = 1SkIa0fw2CZ61lqnhhkJ_

### List all
GET {{baseUrl}}/app/counterparties
Content-Type: application/json
X-API-Key: {{apiKey}}

### List non-existing counterparty
GET {{baseUrl}}/app/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### List existing counterparty
GET {{baseUrl}}/app/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}