#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = 5426459

### List all
GET {{baseUrl}}/db/counterparties
Content-Type: application/json
X-API-Key: {{apiKey}}

### List existing counterparty
GET {{baseUrl}}/db/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}

### List non-existing counterparty
GET {{baseUrl}}/db/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}