#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = 5426459

### Delete existing counterparty
DELETE {{baseUrl}}/db/counterparties?id={{counterpartyId}}
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete non-existing counterparty
DELETE {{baseUrl}}/db/counterparties?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}