#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@counterpartyId = 1SkIa0fw2CZ61lqnhhkJ_

### Update a missing counterparty
PUT {{baseUrl}}/app/counterparties
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "id": "missing", "name": "nevermind" }

### Update existing counterparty
PUT {{baseUrl}}/app/counterparties
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "id": "{{counterpartyId}}", "name": "edited" }