#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@userEmail = user@mail.com

### Delete non-existing user should fail
DELETE {{baseUrl}}/app/users?email=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing user
DELETE {{baseUrl}}/app/users?email={{userEmail}}
Content-Type: application/json
X-API-Key: {{apiKey}}