#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@userId = 38cd09f7-1e69-4b0b-ba67-c3a0b89db466

### Delete non-existing user
DELETE {{baseUrl}}/db/users?id=missing
Content-Type: application/json
X-API-Key: {{apiKey}}

### Delete existing user
DELETE {{baseUrl}}/db/users?id={{userId}}
Content-Type: application/json
X-API-Key: {{apiKey}}