#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test

### Attempt to create the admin user should trigger PK violation error
POST {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "email": "drexa1@hotmail.com", "name": "nevermind" }

### Create user for the first time should suceed
POST {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "email": "user@mail.com", "name": "Test user" }

### Second create attempt should trigger PK violation error
POST {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "email": "user@mail.com", "name": "Test user" }