#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@userEmail = user@mail.com

### Update a missing user should fail
PUT {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "email": "missing", "name": "nevermind" }

### Update existing user
PUT {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{ "email": "{{userEmail}}", "name": "edited" }