#@no-redirect
@baseUrl = http://localhost:3001
@apiKey = test
@userId = 38cd09f7-1e69-4b0b-ba67-c3a0b89db466

### Update a missing user
PUT {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "id": "missing",
    "name": "nevermind"
}

### Update existing user
PUT {{baseUrl}}/app/users
Content-Type: application/json
X-API-Key: {{apiKey}}

{
    "id": "{{userId}}",
    "name": "edited"
}